######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 20 10:29:03 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

HEADERS += \
    stack.h
