######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 21 10:17:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

HEADERS += \
    BinarySearchTree.h
