######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 18 17:12:45 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

HEADERS += \
    Queue.h
