######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 21 09:15:01 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    BinaryTree.h

SOURCES += \
    main.cpp
