######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 21 20:21:04 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += demo.cpp \
    test.cpp

HEADERS += \
    RedBlackTree.h
