######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 20 09:28:44 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += List.h

SOURCES += \
    main.cpp
