######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 20 11:02:15 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

HEADERS += \
    ListQueue.h
