######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 22 22:00:27 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
