######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 22 21:56:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
