######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 19 16:29:18 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += \
    main.cpp \
    STL_List.cpp

HEADERS += \
    List.h
