######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 22 10:29:29 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

HEADERS += \
    HashMap.h \
    LinearMap.h
