######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 22 11:52:39 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    HeapSort.cpp

HEADERS += \
    Heap.h
