######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 18 15:00:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    MyUtil.h \
    MyStack.h
SOURCES += main.cpp
